name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

      # Add steps for pushing to Docker Hub and deployment as needed

      - name: Build Docker Image
        run: docker build -t mortgage-calculator .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Image to Docker Hub
        run: |
          docker tag mortgage-calculator ${{ secrets.DOCKER_USERNAME }}/mortgage-calculator
          docker push ${{ secrets.DOCKER_USERNAME }}/mortgage-calculator
