name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your.email@example.com'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          token: ${{ secrets.GH_PAT }}  # Use your PAT for checkout

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Calculate new version and tag
        run: |
          NEW_TAG="v$(date +%Y%m%d%H%M%S)"
          echo "New Tag: $NEW_TAG"
          git tag $NEW_TAG
          git push https://${{ secrets.GH_PAT }}@github.com/MeirBen/mortgage.git --tags


      - name: Build Docker Image
        run: docker build -t mortgage-calculator:$NEW_TAG .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Image to Docker Hub with tag
        run: |
          docker tag mortgage-calculator:$NEW_TAG ${{ secrets.DOCKER_USERNAME }}/mortgage-calculator:$NEW_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/mortgage-calculator:$NEW_TAG
